version: "3.9"

services:
  postgres:
    image: postgres:15-alpine # Updated to the latest PostgreSQL version
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: mypass
      POSTGRES_DB: simple_bank
    ports:
      - "5432:5432"
    volumes:
      - data-volume:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine # Using the latest Redis version
    ports:
      - "6379:6379" # Added for clarity, though Redis uses default port 6379

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "9090:9090"
    environment:
      DB_SOURCE: postgresql://root:mypass@postgres:5432/simple_bank?sslmode=disable
      REDIS_ADDRESS: redis:6379
    depends_on:
      - postgres
      - redis
    entrypoint: ["/app/wait-for.sh", "postgres:5432", "--", "/app/start.sh"]
    command: ["/app/main"]

volumes:
  data-volume:
